name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install `protoc` and `protoc-gen-grpc-java`
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          
          # Download and install protoc-gen-grpc-java
          PROTOC_VERSION=3.19.4
          GRPC_VERSION=1.44.1
          mkdir -p ~/protoc && cd ~/protoc
          curl -LO https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/${GRPC_VERSION}/protoc-gen-grpc-java-${GRPC_VERSION}-linux-x86_64.exe
          chmod +x protoc-gen-grpc-java-${GRPC_VERSION}-linux-x86_64.exe
          sudo mv protoc-gen-grpc-java-${GRPC_VERSION}-linux-x86_64.exe /usr/local/bin/protoc-gen-grpc-java

          # Ensure protoc and plugin are executable
          echo "✅ Installed protoc version:"
          protoc --version
          echo "✅ Checking protoc-gen-grpc-java"
          ls -l /usr/local/bin/protoc-gen-grpc-java
          chmod +x /usr/local/bin/protoc-gen-grpc-java

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and build
        run: mvn clean install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GasPumpSystem-jar
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures 'test' runs only after 'build' succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Restore Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: GasPumpSystem-jar
          path: target

      - name: Run unit tests
        run: mvn test

  verify:
    runs-on: ubuntu-latest
    needs: test  # This ensures 'verify' runs only after 'test' succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Restore Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: GasPumpSystem-jar
          path: target

      - name: Verify build success
        run: mvn verify
