name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Protobuf Compiler
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler

      - name: Verify Protobuf Version
        run: protoc --version

      - name: Build Project
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Build and Package JAR
        run: mvn package

      - name: Archive JAR File
        uses: actions/upload-artifact@v4
        with:
          name: gas-pump-system
          path: target/*.jar
