name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and build
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Check if gRPC files are correctly generated
        run: test -d target/generated-sources/protobuf/java || exit 1

      - name: Verify build success
        run: mvn verify

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: GasPumpSystem-jar
          path: target/*.jar
